version: '3'

services:
  sioux-admin-api:
    restart: always
    image: sioux-admin-api
    container_name: sioux-admin-api
    build: .
    volumes: 
      - './build-api:/app'
    ports: 
      - '5001:80'
    environment:
      - VIRTUAL_HOST=api.siouxadmin.tk
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=api.siouxadmin.tk
      - LETSENCRYPT_EMAIL=quoc.tran@sioux.asia

